### ISSUE TITLE
calendario in cerca tata

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#10]
Il calendario usato per scegliere il periodo di servizio nella ricerca della tata non mostra il nome del mese, per cui se mi muovo usando le  frecce nei mesi successivi non riesco a capire immediamente in che mese mi trovo

**Comment by kazhamiakin** [comment]
Si riproduce in dispositivi come SII

**Comment by oskarnrk** [comment]
Fixed library
