### ISSUE TITLE
selezione date in calcola preventivo

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#18]
Se il periodo selezionato è inferiore ai 3 mesi va aggiunto un pop’ up che dice
“ATTENZIONE! La durata minima del servizio è di 3 mesi” e poi si procede normalmente

**Comment by oskarnrk** [comment]
Su accordo con Michele le date vengono cambiate per essere sempre minimo 3 mesi. Se si cambia la data di inizio si porta il termine sempre a minimo 3 mesi. Se si prova a cambiare la data di fine con una che rende il lasso di tempo minori ai 3 mesi si mostra il popup e si fa la stessa cosa in base alla data di inizio.
