### ISSUE TITLE
Interventi grafici

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#22]
- RICHIESTA COLLOQUIO : inserire INFORMATIVO (così si distingue dal colloquio con la tata)
- QUANTO COSTA: c’è un refuso nel testo: la tariffa massima è di 14,64: togliere nei testi riferimenti a prezzi
- Se ci sta aggiungerei anche che Gli unici costi una tantum all’attivazione del contratto sono: 12,00 Euro per il certificato penale della TATA; e, qualora presentato, 10,00 Euro per progetti Buono di Servizio fino a 120 ore, o 20,00 euro per progetti oltre le 120 ore. [Riferimento al QUANTO COSTA]
- TARIFFARIO Va corretto il testo: i valori in rosso si riferiscono alla tariffa per minori portatori di handicap (ai sensi della Legge n.104/1992) . e da TARIFFA DIURNA/FESTIVA/NOTTURNA togliere il testo  Ore settimanali
- testo corretto de IL PRIMO INCONTRO e CONOSCI LA TATA

**Comment by oskarnrk** [comment]
Corretto il testo per "Conosci la tata" mentre per "Il primo incontro" il testo e' solo una frase. Verificare! (chiedo a MT).
Il resto e' fatto.

**Comment by oskarnrk** [comment]
- RICHIESTA COLLOQIO: fatto
- QUANTO COSTA: cambiato il paragrafo con il prezzo con quello nuovo
- TARIFFARIO: testi corretto
- CONOSCI LA TATA: testo nuovo
- IL PRIMO INCONTRO: si attendono indicazioni in quanto il testo nuovo, di una frase, non pare sia corretto
