### ISSUE TITLE
validazione campi tariffario

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#3]
La validazione dei campi della tabella TARIFFA NOTTURNA del tariffario scatta prima che venga premuto il tasto salva

**Comment by mirkoperillo** [comment]
L'obbligo di inserimento di tutti i campi esiste solo per la tabella notturna, le altre due non presentano validazione

**Comment by regolo85** [comment]
Errore dovuto alla condivisione della stessa form di input tra le 3 diverse tabelle. Sono state create 3 diverse form che lavorano in modo indipendente e che mostrano correttamente i campi obbligatori e il pattern specifico di inserimento
