### ISSUE TITLE
Profilo tata

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#5]
Attualmente il profilo della tata non e' allineato a quanto indicato dal mockup05

**Comment by oskarnrk** [comment]
@mirkoperillo mancano titolo di studio e disponibilità. Quello che c'è è stato inserito

**Comment by mirkoperillo** [comment]
aggiunto al profilo tata
titolo di studio -> campo qualification
disponibilita' -> campo available
