### ISSUE TITLE
tariffario salvataggio

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.tataapp#6]
Salvando i dati nel tariffario ci sono strani comportamenti nelle tabelle notturna e festivo.

Sembrano salvati ma al refresh mancano ( questo succede sicuramente per tutti i dati della tabella notturna e per l'ultima colonna di destra della tabella festivo)

**Comment by regolo85** [comment]
Problema dovuto ad una gestione non corretta delle chiamate rest sul salvataggio dell'oggetto. Invece che andare ad aggiornare la lista nel salvataggio delle tabelle si andava di volta in volta a creare una nuova lista. Aggiunto controllo che crea la lista solo se nel db non ci sono già liste, altrimenti ci si limita ad aggiornare la lista presente con i nuovi dati

**Comment by mirkoperillo** [comment]
Il problema sembra continuare.
Caso di test:

se riempo la tabella notturna e salvo, facendo refresh oppure rientrando nella pagina i valori sembrano tenuti.
Nel caso in cui metto un valore all'ultimo campo della colonna di destra della tabella festivo allora perdo il valore del campo e tutti quelli della tabella notturni

**Comment by mirkoperillo** [comment]
Il baco e' corretto.

Il database conteneva una situazione sporca precedente al fix che dava malcomportamenti.
